import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins, Mrs_Sheppards, Josefin_Sans, Istok_Web } from 'next/font/google'
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: '--font-poppins',
  display: 'swap',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const mrsSheppards = Mrs_Sheppards({
  subsets: ["latin"],
  variable: '--font-mrs-sheppards',
  display: 'swap',
  weight: "400",
});
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: '--font-josefin-sans',
  display: 'swap',
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
const istokWeb = Istok_Web({
  subsets: ["latin"],
  variable: '--font-istok-web',
  display: 'swap',
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Lucas Djaja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} 
        ${mrsSheppards.variable} ${josefinSans.variable} ${istokWeb.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
